channels:
  - conda-forge

dependencies:
  - r-base = 3.6
  - r-tidyverse
  - r-palmerpenguins
  - r-sf
  - r-mapview
  - r-gghighlight
  - r-lubridate
  - r-janitor
  - r-usmap
  - r-viridis
  - r-paletteer
  - r-cowplot
  - r-geojsonio
  
