#r-2021-09-06
#r-4.0-2021-05-19

channels:
  - conda-forge
dependencies:
  - r-base = 4.0
  - r-tidyverse
  - r-palmerpenguins
  - r-sf
  - r-mapview
  - r-gghighlight
  - r-lubridate
  - r-janitor
  - r-usmap
  - r-viridis
  - r-paletteer
  - r-cowplot
  
